---
title: ""
output: html_document
---

---

---

<link rel="stylesheet" href="styles.css" type="text/css">

<div class="a"> Check out my academic trail [here](files/Path/path.html)

The map below also shows the cities I have visited so far </div>


```{r include = FALSE}
library(leaflet)
library(dplyr)
library(htmltools)
library(htmlwidgets)
```

```{r echo=FALSE}
city_name <- c("Berlin","London","Paris","Chicago","Zürich","Tokyo","Beijing","Milan","Shanghai","New York","Los Angeles","Sydney","Hawaii","Hong Kong")
longitude <- c("13.405", "-0.118", "2.3522","-87.62","8.541","138.252","116.407","9.190","121.473","-73.935","-118.243","151.209","-155.84","114.17")
latitude <- c("52.52", "51.509", "48.8566","41.881","47.376","36.204","39.904","45.464","31.230","40.7306","34.05","-33.865","19.74","22.302")
df <- data.frame(city_name, longitude, latitude)

df$longitude<-as.numeric(df$longitude)
df$latitude<-as.numeric(df$latitude)
leaflet() %>% 
  addTiles()%>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 1",
    onClick=JS("function(btn, map){ map.setZoom(1); }"))) %>%
  addMarkers(data=df,lng=~longitude,lat=~latitude,popup = ~city_name,clusterOptions = markerClusterOptions()) %>%
  clearBounds() 
```
